//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Ext.rc
//
#define IDST_OBJNAME                    128
#define IDST_AUTHOR                     129
#define IDST_COPYRIGHT                  130
#define IDST_COMMENT                    131
#define IDST_HTTP                       132
#define M_ACTION                        5000
#define M_ACT_P1                        5501
#define M_ACT_P2                        5502
#define M_CONDITION                     6000
#define M_CND_P1                        6501
#define M_CND_P2                        6502
#define M_CND_P3                        6503
#define M_EXPRESSION                    7000
#define M_EXPRESSION2                   7001
#define M_EXPRESSION3                   7002
#define M_EXP_P1                        7500
#define M_EXP_P2                        7501
#define MN_ACTIONS                      20000
#define MN_CONDITIONS                   20001
#define MN_EXPRESSIONS                  20002
#define IDS_BOIDTYPE                    20005
#define IDS_XPOSITION                   20006
#define IDS_YPOSITION                   20007
#define IDS_XSPEED                      20008
#define IDS_YSPEED                      20009
#define IDS_RADIUS                      20010
#define IDS_ANGLE                       20011
#define IDS_STRENGTH                    20012
#define IDS_FIXEDVALUE                  20013
#define IDS_EXPBOIDTYPE                 20014
#define IDS_SELECTOBJECT                20015
#define IDS_WEIGHT                      20016
#define IDS_LOOPNAME                    20017
#define IDS_SPEED                       20018
#define IDS_MAXSPEED                    20019
#define IDS_ACCELERATION                20020
#define IDS_DECELERATION                20021
#define IDS_TURNSPEED                   20022
#define IDS_RANDOMIZATION               20023
#define IDS_ANGLEDIRSETTING             20024
#define IDS_WIDTH                       20025
#define IDS_HEIGHT                      20026
#define IDS_USEANGLES                   20027
#define IDS_USEDIRECTIONS               20028
#define IDS_DEFAULTPARAMETERS           20029
#define IDS_PROP_IDLESPEED              20030
#define IDS_PROP_MAXSPEED               20031
#define IDS_PROP_ACCELERATION           20032
#define IDS_PROP_DECELERATION           20033
#define IDS_PROP_TURNSPEED              20034
#define IDS_PROP_VIEWRADIUS             20035
#define IDS_PROP_AVOIDANCERADIUS        20036
#define IDS_PROP_RANDOMIZATION          20037
#define IDS_PROP_ANGLEDIRSETTING        20038
#define IDS_DEFAULTWEIGHTS              20039
#define IDS_PROP_SEPARATIONWEIGHT       20040
#define IDS_PROP_ALIGNMENTWEIGHT        20041
#define IDS_PROP_COHESIONWEIGHT         20042
#define IDS_FLOCKINGHEADER_TITLE        20043
#define IDS_PROP_CELLSIZE               20044
#define IDS_PROPINFO_CELLSIZE           20045
#define IDS_PROPINFO_IDLESPEED          20046
#define IDS_PROPINFO_MAXSPEED           20047
#define IDS_PROPINFO_ACCELERATION       20048
#define IDS_PROPINFO_DECELERATION       20049
#define IDS_PROPINFO_TURNSPEED          20050
#define IDS_PROPINFO_VIEWRADIUS         20051
#define IDS_PROPINFO_AVOIDANCERADIUS    20052
#define IDS_PROPINFO_RANDOMIZATION      20053
#define IDS_PROPINFO_ANGLEDIRSETTING    20054
#define IDS_PROPINFO_SEPARATIONWEIGHT   20055
#define IDS_PROPINFO_ALIGNMENTWEIGHT    20056
#define IDS_PROPINFO_COHESIONWEIGHT     20057
#define IDS_PROP_AVOIDOBSTACLES         20058
#define IDS_PROPINFO_AVOIDOBSTACLES     20059
#define IDS_PROP_MINSPEED               20060
#define IDS_PROPINFO_MINSPEED           20061
#define IDS_MINSPEED                    20062
#define IDS_USENONE                     20063
#define IDS_PROP_SPEEDDEPENDANTTURN     20064
#define IDS_PROPINFO_SPEEDDEPENDANTTURN 20065
#define IDS_SPEEDDEPENDANTTURN          20066
#define IDS_AVOIDOBSTACLESETTING        20067
#define IDS_HYBRIDDIRANGLE		        20068
#define ID_ADDOBJECTASBOID              25000
#define ID_REMOVEOBJECT                 25001
#define ID_SETIDLESPEED                 25002
#define ID_SETMINSPEED                  25003
#define ID_SETMAXSPEED                  25004
#define ID_SETACCELERATION              25005
#define ID_SETDECELERATION              25006
#define ID_SETTURNSPEED                 25007
#define ID_SETVIEWRADIUS                25008
#define ID_SETAVOIDANCERADIUS           25009
#define ID_SETMOVEMENTRANDOMIZATION     25010
#define ID_SETSEPARATIONWEIGHT          25011
#define ID_SETALIGNMENTWEIGHT           25012
#define ID_SETCOHESIONWEIGHT            25013
#define ID_SETANGLEDIRSETTING           25014
#define ID_SETSPEEDDEPENDANTTURN        25015
#define ID_SETAVOIDOBSTACLES            25016
#define ID_ALLOFTYPE_ATTRACTTOWARDSPOSITION 25017
#define ID_ALLOFTYPE_CHASEAWAYFROMPOSITION 25018
#define ID_ALLOFTYPE_APPLYFORCE         25019
#define ID_WITHINRADIUS_ATTRACTTOWARDPOSITION 25020
#define ID_WITHINRADIUS_CHASEAWAYFROMPOSITION 25021
#define ID_WITHINRADIUS_APPLYFORCE      25022
#define ID_SINGLEBOID_ATTRACTTOWARDSPOSITION 25023
#define ID_SINGLEBOID_CHASEAWAYFROMPOSITION 25024
#define ID_SINGLEBOID_APPLYFORCE        25025
#define ID_LOOPNEIGHBOURBOIDS           25026
#define ID_LOOPBOIDSINRADIUS            25027
#define ID_LOOPBOIDSINRECTANGLE         25028
#define ID_LOOPALLBOIDS                 25029
#define ID_LOOPALLOFTYPE                25030
#define ID_ONLOOPEDBOID                 26000
#define ID_FROMBOIDTYPE_GETIDLESPEED    27000
#define ID_FROMBOIDTYPE_GETMINSPEED     27001
#define ID_FROMBOIDTYPE_GETMAXSPEED     27002
#define ID_FROMBOIDTYPE_GETACCELERATION 27003
#define ID_FROMBOIDTYPE_GETDECELERATION 27004
#define ID_FROMBOIDTYPE_GETTURNSPEED    27005
#define ID_FROMBOIDTYPE_GETBOIDVIEWRADIUS 27006
#define ID_FROMBOIDTYPE_GETAVOIDANCERADIUS 27007
#define ID_FROMBOIDTYPE_GETRANDOMIZATION 27008
#define ID_FROMBOIDTYPE_GETVIEWRADIUS   27009
#define ID_FROMBOIDTYPE_GETSEPARATIONWEIGHT 27010
#define ID_FROMBOIDTYPE_GETALIGNMENTWEIGHT 27011
#define ID_FROMBOIDTYPE_GETCOHESIONWEIGHT 27012
#define ID_FROMOBJECT_GETANGLE          27013
#define ID_FROMOBJECT_GETSPEED          27014
#define ID_FROMOBJECT_GETXSPEED         27015
#define ID_FROMOBJECT_GETYSPEED         27016
#define ID_FROMOBJECT_GETTARGETX        27017
#define ID_FROMOBJECT_GETTARGETY        27018
#define ID_LOOPCURRENT_GETANGLE         27019
#define ID_LOOPCURRENT_GETSPEED         27020
#define ID_LOOPCURRENT_GETXSPEED        27021
#define ID_LOOPCURRENT_GETYSPEED        27022
#define ID_LOOPCURRENT_GETTARGETX       27023
#define ID_LOOPCURRENT_GETTARGETY       27024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40079
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
